### ISSUE TITLE
`sfdisk` should ask which drive to partition

### ISSUE THREAD

**Issue by Dale-Muccignat** [Dale-Muccignat/ArchMirage#10]
Progress on this issue is the subject of branch `sdX`

**Comment by Dale-Muccignat** [comment]
So we know that the following can be used to gather input data:
```
read -p "message: " variable
```
Should be able to use something like `read -p "Choose which drive to install on (a/b/c): " drive`.
Could of things though. We need to find what drives the computer have and make it so it only shows those options. And we need to ensure we can have the format `/dev/sdX` for `sfdisk`.

- Read what drives are available
- Pass drives into input message
- Ensure input is valid
- Pass input drive to `sfdidsk`

**Comment by miragebird** [comment]
"Read what drives are available" -> https://man.archlinux.org/man/lsblk.8.en 

`lsblk`

seems to read out the current disks. We can use this to:

1 - list disks to user and ask the user to input the entire path, eg `/dev/sdX`
2 - somehow assign option numbers to the outputs of lsblk so the end user on specifies a number, eg 1

**Comment by Dale-Muccignat** [comment]
After some trial and error I got:
```
lsblk --output NAME,TYPE | grep 'disk' | cut -d" " -f1
```
the `|` character is a pipe symbol which passed the output of the function on the left, to the one on the right. So grep returns any link with 'disk' in it and then cut splits each string so that things seperated by a space " " are seperate. f1 returns the first element of each split string.

For me this returns
```
sda
sdb
sdc
```
I can then assign that output to a variable using this weird notation:
```
x=$(lsblk --output NAME,TYPE | grep 'disk' | cut -d" " -f1)
```
which we can print with `echo $x`

**Comment by miragebird** [comment]
Nice! my only concern with the current output, is we probably need to include drive info to the user so they know what drive is what. Maybe like drive size and make?

**Comment by Dale-Muccignat** [comment]
Good point, something like `lsblk --output NAME,TYPE,SIZE,MODEL | grep 'disk'` could be the output we show the user. Will still need the above to narrow down the possible letters so we can have input error checking.
For me, that outputs:
```
sda    disk 931.5G Samsung SSD 860 QVO 1TB
sdb    disk 119.2G Samsung SSD 840 PRO Series
sdc    disk 447.1G WDC WDS480G2G0A-00JH30
```

**Comment by Dale-Muccignat** [comment]
Although, we might want to see the partitions and full serial details

**Comment by miragebird** [comment]
I'm personally not concerned about seeing partitions, wouldn't this make the drive selection harder?

**Comment by Dale-Muccignat** [comment]
Probably. I was mostly thinking in the case that someone has identical drives, maybe just the serial number to cover our bases?

**Comment by miragebird** [comment]
That's a fair use case, maybe we dump all the info onto screen including "current" partitions, then promt the user for simplifed options to choose from, eg `sda`, or `1`

**Comment by Dale-Muccignat** [comment]
An option:
```
#!/bin/bash/
x="================================================================="
echo $x
lsblk --output NAME,TYPE,SIZE,MODEL,SERIAL | grep 'disk'
echo $x
y=$(lsblk --output NAME,TYPE,SIZE,MODEL,SERIAL | grep 'disk' | cut -d" " -f1 | tr '\n' '/')
read -p "Select one of [${y%?}]: " drive
```
With an output of:
```
=================================================================
sda    disk 931.5G Samsung SSD 860 QVO 1TB      S4CZNF0N113840Y
sdb    disk 119.2G Samsung SSD 840 PRO Series  S1ANNSADB08612R
sdc    disk 447.1G WDC WDS480G2G0A-00JH30   1943CA455401
=================================================================
Select one of [sda/sdb/sdc]: 
```

**Comment by Dale-Muccignat** [comment]
Found a drive name of 'mmcblk0' for my laptop. Partitions are labels with mmcblk0p1,mmcblk0p2,etc rather than sda1,sda2. Going to need some smart code...

**Comment by miragebird** [comment]
mmc, seems to be SD card storage fyi, there could be actualy use cases to install arch on an SD card?

**Comment by Dale-Muccignat** [comment]
I think we merge branch sdx for now to resolve this issue and creat a new issue specifically about drive names other than sdx
